name: Run and Commit Jupyter Notebook

on:
  push:
    branches:
      - main
    paths:
      - 'data.csv' # Only run when the data.csv file is changed

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute eda.ipynb --inplace

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add eda.ipynb
          # Commit only if there are changes
          git diff --staged --quiet || git commit -m "Automated EDA: Update Jupyter Notebook with new results"
          git push
